site_name: 3D vasculiciar Analysis
repo_url: https://github.com/Merck/3D_Tumor_Lightsheet_Analysis_Pipeline
site_url: https://merck.github.io/3D_Tumor_Lightsheet_Analysis_Pipeline/
theme:
  name: material
  font:
    text: Ubuntu
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - codehilite
  - pymdownx.highlight
  - footnotes

plugins:
 - search
 - mkdocstrings

nav:
  - index.md
  - Methodology Overview:
    - methodology_overview.md
  - Code Overview:
#    - code_overview.md
    - prerequisites.md
    - code usuage.md
    - config.md
  - Modules:
    - Preprocessing: Modules/preprocessing.md
    - Segmentation: Modules/segmentation.md
    - Segmentation Postprocessing: Modules/segmentation_postprocessing.md
    - Distance Transform: Modules/distance_transform.md
    - Profiles: Modules/profiles.md
